### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by lcxyhhxi** [xinyao27/next-devtools#1]
<img width="940" alt="image" src="https://github.com/xinyao27/next-devtools/assets/23306072/47c3c886-ea15-4ea2-ae67-58cdc8a31dd6">

大佬您好我试了一下按照文档但是没跑起来不知道咋回事

**Comment by xinyao27** [comment]
You can switch `next.config.mjs` -> `next.config.js`
Or adjust the import method to `import { withNextDevtools } from '@next-devtools/core/plugin'`
