### ISSUE TITLE
fix: in windows the url of the devtools is incorrect

### ISSUE THREAD

**Issue by nagy-nabil** [xinyao27/next-devtools#10]
### 🐛 The bug

the url in windows instead of "localhost" prints the current username, here's an example
![image](https://github.com/xinyao27/next-devtools/assets/65990275/e3425d46-6578-4e64-941a-a3fca7442f72)

### 🛠️ To reproduce

start the provided example in windows

### 🌈 Expected behavior

in windows url suppose to be "localhost" like in linux
here's the same example on my machine in linux
![image](https://github.com/xinyao27/next-devtools/assets/65990275/1a2890d9-bf9d-4615-94e1-c87d58ebdd80)

**Comment by xinyao27** [comment]
Except for the incorrect URL, are all other functions working properly?

I am planning to remove the log of NextDevtools because it seems a bit confusing.
