### ISSUE TITLE
feat: Security.md file

### ISSUE THREAD

**Issue by OhB00** [xinyao27/next-devtools#11]
### 🆒 Your use case

I would like to be able to disclose a security vulnerability. 

### 🆕 The solution you'd like

It would be great if you could create a SECURITY.md file and enable [Private Vulnerability Reporting](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository).

**Comment by xinyao27** [comment]
Thank you for the suggestion!
