### ISSUE TITLE
docs: Credits back to Nuxt DevTools

### ISSUE THREAD

**Issue by Atinux** [xinyao27/next-devtools#13]
### 📚 Is your documentation request related to a problem?

I think this would be nice as this is very inspired by it, and giving credits in the open source is IMO the minimum you can do 😊 

### 🔍 Where should you find it?

Linking to https://github.com/nuxt/devtools

**Comment by xinyao27** [comment]
Of course, it has already been updated in the readme. Inspired by NuxtDevtools.
