### ISSUE TITLE
The requested module '@next/env' is a CommonJS module, which may not support all module.exports as named exports

### ISSUE THREAD

**Issue by Talent30** [xinyao27/next-devtools#6]
```
file:///home/ubuntu/node_modules/@next-devtools/core/dist/rpc-IPLRGAWM.js:106
import { loadEnvConfig } from "@next/env";
         ^^^^^^^^^^^^^
SyntaxError: Named export 'loadEnvConfig' not found. The requested module '@next/env' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@next/env';
const { loadEnvConfig } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:214:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
```

```
Operating System:
  Platform: linux
  Arch: arm64
  Version: #13-Ubuntu SMP Sat Nov 18 06:20:29 UTC 2023
Binaries:
  Node: 21.5.0
  npm: 10.2.4
  Yarn: N/A
  pnpm: 8.10.5
Relevant Packages:
  next: 14.0.5-canary.34
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: standalone
```

**Comment by xinyao27** [comment]
Can you provide a reproducible repository?

By the way, are you a global install? Your file path looks a bit strange.

**Comment by Talent30** [comment]
> Can you provide a reproducible repository?
> 
> By the way, are you a global install? Your file path looks a bit strange.

No, it's a monorepo,

[here](https://codesandbox.io/p/devbox/wonderful-beaver-s3vwxt?file=%2Fapps%2Fdocs%2Fnext.config.js%3A6%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqw83vly00062e6677p7d2wm%2522%252C%2522sizes%2522%253A%255B53.41772151898734%252C46.58227848101266%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqw83vly00022e66kg2ncmo3%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqw83vly00042e66g81x9igs%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqw83vly00052e663ux23jhc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqw83vly00022e66kg2ncmo3%2522%253A%257B%2522id%2522%253A%2522clqw83vly00022e66kg2ncmo3%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqw83vly00012e6645rpii0u%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqw83vly00012e6645rpii0u%2522%257D%252C%2522clqw83vly00052e663ux23jhc%2522%253A%257B%2522id%2522%253A%2522clqw83vly00052e663ux23jhc%2522%252C%2522activeTabId%2522%253A%2522clqw8b876003c2e66vt1jcd2v%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3001%252C%2522id%2522%253A%2522clqw8b876003c2e66vt1jcd2v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%257D%252C%2522clqw83vly00042e66g81x9igs%2522%253A%257B%2522id%2522%253A%2522clqw83vly00042e66g81x9igs%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqw83vly00032e663hw6866o%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clqw83w060025egix3zyj5xkv%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqw83vly00032e663hw6866o%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) is the repo

**Comment by xinyao27** [comment]
I tried to fix this error, but there are other issues in the codesandbox environment, such as the inability to communicate data between localhost and project/devtools. I am looking for a solution to this problem.

**Comment by Talent30** [comment]
> I tried to fix this error, but there are other issues in the codesandbox environment, such as the inability to communicate data between localhost and project/devtools. I am looking for a solution to this problem.

Thank you very much! this is an awesome lib, would be nice if we can bring some of the [RSC devtool](https://chromewebstore.google.com/detail/rsc-devtools/jcejahepddjnppkhomnidalpnnnemomn) features into this lib.

**Comment by xinyao27** [comment]
> > I tried to fix this error, but there are other issues in the codesandbox environment, such as the inability to communicate data between localhost and project/devtools. I am looking for a solution to this problem.
> 
> Thank you very much! this is an awesome lib, would be nice if we can bring some of the [RSC devtool](https://chromewebstore.google.com/detail/rsc-devtools/jcejahepddjnppkhomnidalpnnnemomn) features into this lib.

Maybe there will be a chance in the future.
